version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - "80:80"
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=mojtaba386386
      - DATABASE_NAME=fasapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mojtaba386386
      - POSTGRES_DB=fasapi
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: