"""add phone number

Revision ID: 07be24f0d1cc
Revises: 0a35e1a400b4
Create Date: 2023-05-04 22:09:38.731955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07be24f0d1cc'
down_revision = '0a35e1a400b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
